---
language: python
services: docker

env:
  global:
    - ROLE_NAME: envoyproxy

install:
  # Install test dependencies.
  - pip install ansible-lint

  # Check ansible-lint version
  - ansible-lint --version

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME fabiocruzcoelho.$ROLE_NAME
  - cd fabiocruzcoelho.$ROLE_NAME

script:
  # Basic ansible-lint
  - ansible-lint *.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
